Completed prep-javascript-dom-events Exercise
BenGrimmius/prep-0422-code-solutions pull request #17
Opened 2022-04-30 16:45 UTC by BenGrimmius

<img width="1512" alt="Screen Shot 2022-04-30 at 9 42 23 AM" src="https://user-images.githubusercontent.com/103142603/166114636-e7c5b43e-3427-4e5a-87c0-02a46418ad68.png">

2022-04-30 16:45 UTC, BenGrimmius commented
For some reason I couldn't get all of my logs to show in browser.

2022-05-02 13:48 UTC, thebearingedge requested changes

2022-05-02 13:48 UTC, thebearingedge commented on prep-javascript-dom-events/index.html
> +    }
Hi Ben, for the `'DOMContentLoaded'` event, you want to add the listener to the document.

```js
    document.addEventListener('DOMContentloaded', myFunction);
    function myFunction() {
      console.log('Content Loaded');
    }
```

And for the `'click'` event you want to listen to the button.

```js
    $helloWorld.addEventListener('click', myFunction3);
    function myFunction3() {
      'click';
      console.log('Hello World');
    }
```

2022-05-03 01:55 UTC, BenGrimmius reviewed
<img width="1512" alt="Screen Shot 2022-05-02 at 6 55 18 PM" src="https://user-images.githubusercontent.com/103142603/166394049-4f5f70d2-9697-4d09-bf55-38470de69f60.png">

2022-05-03 14:02 UTC, thebearingedge approved these changes

2022-05-04 00:43 UTC, merged